USE assignment;
CREATE TABLE dept
(
deptno INT(2) NOT NULL PRIMARY KEY DEFAULT 0,
dname VARCHAR(14),
loc VARCHAR(13)
);
INSERT INTO dept VALUES(10,"ACCOUNTING","NEW YORK");
INSERT INTO dept VALUES(20,"RESEARCH","DALLAS");
INSERT INTO dept VALUES(30,"SALES","CHICAGO");
INSERT INTO dept VALUES(40,"OPERATIONS","BOSTON");