spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springapi?useSSL=false&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
    hibernate:
      ddl-auto: update

